### ISSUE TITLE
Segmentation fault on Manjaro

### ISSUE THREAD

**Issue by HeroS3c** [AkshayMohan/PRTBruteforce#1]
By just copying and pasting the example I get two warnings (due to sequence points) 
```
bruteforce.c:148:65: warning: operation on ‘i’ may be undefined [-Wsequence-point]
  148 |    bfHandle->bfText[i] = bfHandle->bfData[(bfHandle->bfCurrIdx[i--] = 0)];
      |                                                                ~^~
bruteforce.c:156:21: warning: operation on ‘bfHandle->bfUpdIdx’ may be undefined [-Wsequence-point]
  156 |    bfHandle->bfText[++bfHandle->bfUpdIdx] = bfHandle->bfData[(bfHandle->bfCurrIdx[bfHandle->bfUpdIdx] = 0)];
```

Solved by just changing line 148, from:
`bfHandle->bfText[i] = bfHandle->bfData[(bfHandle->bfCurrIdx[i--] = 0)];`
to
` bfHandle->bfText[i] = bfHandle->bfData[(bfHandle->bfCurrIdx[i] = 0)];
      i--;`

it's a small mistake, but please make a fix! this makes a segmentation fault on execution time on my system.

**Comment by AkshayMohan** [comment]
This has been fixed, thanks for your report.
